user2 = User.create!(email: "example@gmail.com")
user1 = User.create!(email: "email.anastassia@gmail.com")

url1 = ShortURL.create_from_long!(user1, 'www.wikipedia.com')
url2 = ShortURL.create_from_long!(user1, 'www.stackoverflow.com')
url3 = ShortURL.create_from_long!(user2, 'www.google.com')
url4 = ShortURL.create_from_long!(user1, 'www.google.com')
url5 = ShortURL.create_from_long!(user2, 'www.pinterest.com')

Visit.record_visit!(user1, url1)
Visit.record_visit!(user1, url2)
Visit.record_visit!(user1, url3)
Visit.record_visit!(user1, url3)
Visit.record_visit!(user1, url4)
Visit.record_visit!(user2, url1)
Visit.record_visit!(user2, url5)
Visit.record_visit!(user2, url4)
